Repository solidjs/solid-docs, pull requests merged in 2023-07, with the labels that each got.

#281 Overview Page
  content/index.mdx
Labels: improve documentation, in progress

#297 Removed start content and cleaned up code
  .prettierrc
  .prettierrc.json
  content/start.tsx
  src/components/ApiSection.tsx
  src/components/Button.tsx
  src/components/ContributorsList.tsx
  src/components/Logo.tsx
  src/components/Main.tsx
  src/components/Preferences.tsx
  src/components/Snippet.tsx
  src/components/Tabs.tsx
  src/components/configurable/IfConfig.tsx
  src/components/context/ConfigContext.tsx
  src/components/nav/Nav.tsx
  src/components/nav/NavHeader.tsx
  src/components/nav/Summary.tsx
  src/root.tsx
Labels: site improvement

#298 Fix typo on solid-primitives page
  content/guides/foundations/solid-primitives.mdx
Labels: typo or grammar fix
