Repository solidjs/solid-docs, pull requests merged in 2024-05, with the labels that each got.

#632 [BugFix] More robust route root check
  src/i18n/config.ts
  src/i18n/helpers.ts
  src/ui/edit-page-link.tsx
  src/ui/layout.tsx
  src/ui/page-issue-link.tsx
  src/utils/route-metadata-helper.ts
Labels: pending review

#651 new testing guide (first draft)
  src/routes/guides/data.json
  src/routes/guides/deploying-your-app.mdx
  src/routes/guides/testing.mdx
Labels: pending review

#718 Expand info on `<A />` reference to include `<a />`
  src/routes/solid-router/reference/components/a.mdx
Labels: improve documentation

#654 Improve documentation for cache functions
  src/routes/solid-router/reference/data-apis/cache.mdx
Labels: improve documentation, pending review
