Repository solidjs/solid-docs, pull requests merged in 2024-03, with the labels that each got.

#494 Add i18n support to route architecture
  CONTRIBUTING.md
  package.json
  pnpm-lock.yaml
  scripts/collections/build-file-tree.mjs
  scripts/collections/create-flat-entry-list.mjs
  scripts/collections/create-nav-tree.mjs
  scripts/collections/index.mjs
  scripts/collections/schemas.mjs
  scripts/collections/utils/create-dir.mjs
  scripts/collections/utils/get-dir-data.mjs
  scripts/collections/utils/get-frontamtter.mjs
  scripts/collections/utils/write-file.mjs
  scripts/create-i18n-entries.mjs
  scripts/create-i18n-tree.mjs
  scripts/generateSitemap.js
  solid-collections.mjs
  src/app.tsx
  src/i18n/config.ts
  src/i18n/dictionaries/default.ts
  src/i18n/dictionaries/index.ts
  src/i18n/dictionaries/pt-br.ts
  src/i18n/helpers.ts
  src/i18n/i18n-context.tsx
  src/i18n/translator.ts
  src/routes/[...404].mdx
  src/routes/[...404].tsx
  src/routes/pt-br/index.mdx
  src/routes/pt-br/quick-start.mdx
  src/styles.css
  src/ui/button-link.tsx
  src/ui/docs-layout.tsx
  src/ui/edit-page-link.tsx
  src/ui/i18n-anchor.tsx
  src/ui/image-links.tsx
  src/ui/layout.tsx
  src/ui/layout/contribute.tsx
  src/ui/layout/hero.tsx
  src/ui/layout/main-header.tsx
  src/ui/layout/main-navigation.tsx
  src/ui/layout/prev-next-links.tsx
  src/ui/layout/table-of-contents.tsx
  src/ui/markdown-components.tsx
  src/ui/not-found.tsx
  src/ui/page-issue-link.tsx
  src/ui/pagination.tsx
  src/ui/quick-links.tsx
  vite.config.ts
Labels: feature, i18n

#572 Add lunaria
  .gitignore
  lunaria.config.json
  lunaria/styles.css
  package.json
  pnpm-lock.yaml
  public/robots.txt
  src/i18n/dictionaries/en/ui.ts
  src/i18n/dictionaries/index.ts
  src/i18n/dictionaries/pt-br/ui.ts
Labels: site improvement, i18n

#523 theme native scrollbars + scrollbar fixes
  public/scripts/browser-specific.js
  src/entry-server.tsx
  src/styles.css
  src/styles/expressive-code.css
  src/ui/layout.tsx
  src/ui/layout/hero.tsx
  src/ui/markdown-components.tsx
Labels: site improvement, a11y

#576 Fix table of contents race condition issue
  src/ui/docs-layout.tsx
  src/ui/layout.tsx
  src/ui/layout/side-panel.tsx
  src/ui/layout/table-of-contents.tsx
Labels: bug

#585 Add Kodiak 🤖
  .kodiak.toml
Labels: feature, site improvement

#579 update `onCleanup`
  src/routes/reference/lifecycle/on-cleanup.mdx
Labels: automerge

#590 Projects top navigation
  global.d.ts
  scripts/collections/index.mjs
  scripts/create-i18n-entries.mjs
  scripts/create-i18n-tree.mjs
  src/app.tsx
  src/entry-server.tsx
  src/i18n/dictionaries/index.ts
  src/i18n/helpers.ts
  src/routes/[...404].tsx
  src/routes/pt-br/solid-router/index.mdx
  src/routes/pt-br/solid-router/quick-start.mdx
  src/routes/reference/data.json
  src/routes/routing/data.json
  src/routes/routing/ssr.mdx
  src/routes/solid-router/advanced-concepts/alternative-routers.mdx
  src/routes/solid-router/advanced-concepts/data.json
  src/routes/solid-router/advanced-concepts/dynamic-routes.mdx
  src/routes/solid-router/advanced-concepts/nested-routes.mdx
  src/routes/solid-router/data.json
  src/routes/solid-router/getting-started/data.json
  src/routes/solid-router/getting-started/defining-routes.mdx
  src/routes/solid-router/getting-started/installation-and-setup.mdx
  src/routes/solid-router/getting-started/linking-routes.mdx
  src/routes/solid-router/index.mdx
  src/routes/solid-router/migration.mdx
  src/routes/solid-router/reference/components/a.mdx
  src/routes/solid-router/reference/components/data.json
  src/routes/solid-router/reference/components/navigate.mdx
  src/routes/solid-router/reference/components/route.mdx
  src/routes/solid-router/reference/components/router.mdx
  src/routes/solid-router/reference/data-apis/action.mdx
  src/routes/solid-router/reference/data-apis/cache.mdx
  src/routes/solid-router/reference/data-apis/create-async.mdx
  src/routes/solid-router/reference/data-apis/data.json
  src/routes/solid-router/reference/data-apis/response-helpers.mdx
  src/routes/solid-router/reference/data.json
  src/routes/solid-router/reference/load-functions/data.json
  src/routes/solid-router/reference/load-functions/load.mdx
  src/routes/solid-router/reference/primitives/data.json
  src/routes/solid-router/reference/primitives/use-before-leave.mdx
  src/routes/solid-router/reference/primitives/use-is-routing.mdx
  src/routes/solid-router/reference/primitives/use-location.mdx
  src/routes/solid-router/reference/primitives/use-match.mdx
  src/routes/solid-router/reference/primitives/use-navigate.mdx
  src/routes/solid-router/reference/primitives/use-params.mdx
  src/routes/solid-router/reference/primitives/use-search-params.mdx
  src/routes/solid-router/rendering-modes/data.json
  src/routes/solid-router/rendering-modes/spa.mdx
  src/routes/solid-router/rendering-modes/ssr.mdx
  src/ui/docs-layout.tsx
  src/ui/layout.tsx
  src/ui/layout/main-header.tsx
  src/ui/layout/main-navigation.tsx
  src/ui/layout/mobile-navigation.tsx
  src/ui/logo.tsx
  vite.config.ts
Labels: site improvement

#594 Update to latest SolidStart
  app.config.ts
  package.json
  pnpm-lock.yaml
  src/app.tsx
Labels: site improvement

#595 Move to Netlify Edge
  app.config.ts
Labels: site improvement

#602 Move out of Edge / Prerender routes
  app.config.ts
  src/routes/reference/reactive-utilities/on.mdx
  src/routes/solid-router/advanced-concepts/dynamic-routes.mdx
  src/routes/solid-router/getting-started/defining-routes.mdx
  src/routes/solid-router/getting-started/installation-and-setup.mdx
  src/routes/solid-router/getting-started/linking-routes.mdx
  src/routes/solid-router/reference/components/navigate.mdx
  src/routes/solid-router/reference/data-apis/cache.mdx
  src/routes/solid-router/reference/load-functions/load.mdx
  src/routes/solid-router/reference/primitives/use-location.mdx
  src/routes/solid-router/rendering-modes/ssr.mdx
Labels: site improvement

#603 fix: custom native scrollbar on light theme is using the dark theme
  src/styles.css
Labels: bug
