Repository solidjs/solid-docs, pull requests merged in 2024-04, with the labels that each got.

#643 manage dark/light theming with inline `<script>` to prevent flash
  src/entry-server.tsx
Labels: pending review

#644 fixed cls issue caused by ch units, fixed horizontal overflow issues
  src/ui/docs-layout.tsx
  src/ui/layout.tsx
  src/ui/layout/main-header.tsx
  src/ui/layout/mobile-navigation.tsx
Labels: bug, site improvement

#682 Anchor Node version to `20.x` on GitHub releases
  .github/workflows/orama_sync.yml
Labels: bug

#683 Fix tab indicator re-sliding on navigation
  src/ui/layout/main-navigation.tsx
Labels: bug

#670 feat: add solid meta docs
  app.config.ts
  global.d.ts
  scripts/collections/index.mjs
  src/routes/solid-meta/data.json
  src/routes/solid-meta/getting-started/client-setup.mdx
  src/routes/solid-meta/getting-started/data.json
  src/routes/solid-meta/getting-started/installation-and-setup.mdx
  src/routes/solid-meta/getting-started/server-setup.mdx
  src/routes/solid-meta/index.mdx
  src/routes/solid-meta/reference/data.json
  src/routes/solid-meta/reference/meta/base.mdx
  src/routes/solid-meta/reference/meta/data.json
  src/routes/solid-meta/reference/meta/link.mdx
  src/routes/solid-meta/reference/meta/meta.mdx
  src/routes/solid-meta/reference/meta/metaprovider.mdx
  src/routes/solid-meta/reference/meta/style.mdx
  src/routes/solid-meta/reference/meta/title.mdx
  src/ui/layout.tsx
  src/ui/layout/main-header.tsx
Labels: feature, improve documentation, site improvement, in progress

#694 add `createStore` to `/reference`
  src/routes/reference/store-utilities/create-store.mdx
  src/routes/reference/store-utilities/data.json
Labels: improve documentation

#687 fix: delay theme icon load
  src/data/theme-provider.tsx
  src/ui/layout/theme-selector.tsx
Labels: bug
