Repository solidjs/solid-docs, pull requests merged in 2024-09, with the labels that each got.

#878 Update dependencies
  package.json
  pnpm-lock.yaml
Labels: site improvement

#879 Fix hard nav to "/reference" pages
  src/routes/solid-router/reference/primitives/use-match.mdx
  src/ui/layout/main-navigation.tsx
Labels: bug

#882 improve translations docs by expanding on current instructions
  CONTRIBUTING.md
Labels: i18n

#884 remove hardcoded Solid-Router version from docs
  src/routes/solid-router/index.mdx
Labels: bug

#874 add docs for `bool:`
  src/routes/reference/jsx-attributes/bool.mdx
  src/routes/reference/jsx-attributes/data.json
Labels: wait to merge, solid 1.9

#866 add docs for `handleEvent` object syntax
  src/middleware/legacy-routes-redirect.ts
  src/routes/concepts/components/event-handlers.mdx
  src/routes/configuration/typescript.mdx
  src/routes/reference/jsx-attributes/data.json
  src/routes/reference/jsx-attributes/on-and-oncapture.mdx
  src/routes/reference/jsx-attributes/on.mdx
  src/routes/reference/jsx-attributes/on_.mdx
Labels: wait to merge, solid 1.9

#892 use server clarification (must be async)
  src/routes/solid-start/reference/server/use-server.mdx
Labels: pending review

#902 Add TS/JS tabs and update from `load()` to `preload()`
  src/routes/solid-start/building-your-application/data-loading.mdx
Labels: solid-router

#903 Adds type and lint checks to CI
  .eslintrc.cjs
  .eslintrc.json
  .github/workflows/static_checks.yml
  app.config.ts
  package.json
  pnpm-lock.yaml
  src/app.tsx
  src/data/get-nav.tsx
  src/data/page-state.tsx
  src/data/theme-provider.tsx
  src/entry-client.tsx
  src/i18n/dictionaries/index.ts
  src/i18n/helpers.ts
  src/i18n/translator.ts
  src/ui/eraser-link/index.tsx
  src/ui/layout/hero-code-snippet.tsx
  src/ui/layout/table-of-contents.tsx
  src/ui/logo.tsx
  src/ui/pagination.tsx
  tailwind.config.ts
  tsconfig.json
Labels: site improvement
